### ISSUE TITLE
Images are flipped properly, but the image mask(?) is not

### ISSUE THREAD

**Issue by ClubEdNZ** [Jerakin/defold-runtime-atlas#2]
If you add a background sprite behind the sprite and sprite1 in the go.collection example, any irregularly shaped sprite will display an upside-down mask in the background sprite, while the image itself is right-side-up.

![image](https://github.com/user-attachments/assets/6f05cd94-4bcf-47dd-822f-4127e2f02c15)

normal image:
![image](https://github.com/user-attachments/assets/d87b3032-e7dc-403b-bf86-4458d9b8c505)

Any idea what's happening here?

**Comment by Jerakin** [comment]
I am unsure what changes you have made. Could you zip up the project with your changes and send it over?

**Comment by ClubEdNZ** [comment]
Here you go. Basically, I just swapped out one of the images with a tree, and added a background sprite behind the other sprites.

[defold-runtime-atlas-main-upsidedown.zip](https://github.com/user-attachments/files/16944563/defold-runtime-atlas-main-upsidedown.zip)

**Comment by Jerakin** [comment]
I see the error now. It was some faulty image flipping code, but lucky me they added an option to do it on image load so I just removed my old code and replaced it with theirs.

I also added an option to premultiply the alpha, which you will need to set to true for the alpha to look correct.

(Fixed in #3)

**Comment by ClubEdNZ** [comment]
thanks for the fix!
I noticed flip_vertically was being ignored in get_package_data, so I changed it to this (not that I know why one might to mess with flip vertically):

local img = image.load(buffer, {flip_vertically=options.flip_vertically or options.flip_vertically == nil, premultiply_alpha=options.premultiply_alpha or false})

**Comment by Jerakin** [comment]
Yeah, probably always need the vertical flip (or else all your imported images will be upside down), so didn't bother exposing that :)
